# Generated by Django 3.1 on 2021-07-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pro_id',
            field=models.CharField(max_length=4),
        ),
    ]
