# Generated by Django 3.1 on 2021-07-19 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210719_2336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
