# Generated by Django 3.1 on 2021-07-20 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210720_1651'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Work',
        ),
    ]
