# Generated by Django 3.1 on 2021-07-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='header',
            field=models.CharField(default='Home', max_length=2000),
            preserve_default=False,
        ),
    ]
