# Generated by Django 3.1 on 2021-07-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_work_header'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Work',
        ),
    ]
