# Generated by Django 3.1 on 2021-07-22 18:02

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_delete_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=2000, null=True)),
                ('user', models.CharField(choices=[], max_length=2000)),
                ('work', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/<django.db.models.fields.related.ForeignKey>/<ckeditor.fields.RichTextField>')),
                ('status', models.CharField(blank=True, choices=[('Not Completed', 'Not Completed'), ('Completed', 'Completed'), ('Hidden', 'Hidden')], max_length=20, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='app.project')),
            ],
        ),
    ]
