# Generated by Django 3.1 on 2021-07-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='user',
            field=models.CharField(choices=[], max_length=2000, null=True),
        ),
    ]
