# Generated by Django 3.1 on 2021-07-23 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210723_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='file',
        ),
    ]
