# Generated by Django 3.1 on 2021-07-23 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app.work'),
        ),
    ]
