# Generated by Django 3.1 on 2021-07-23 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210723_1151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
