# Generated by Django 3.1 on 2021-07-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20210723_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='File', max_length=1000),
            preserve_default=False,
        ),
    ]
