# Generated by Django 3.1 on 2021-07-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_file_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
